GET http://localhost:8080/api/v1/flowers

###
POST http://localhost:8080/api/v1/flowers
Content-Type: application/json

{
  "flowerType": "Tulip",
  "sepalLength": 100,
  "color": "Blue",
  "price": 100
}
