name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean install

    - name: Run Tests
      run: mvn test

    - name: Install HTTPie
      run: |
        sudo apt-get update
        sudo apt-get install httpie
      shell: bash

    - name: Test GET Request
      run: |
        http --check-status GET http://localhost:8080/api/flowers
      shell: bash

    - name: Test POST Request
      run: |
        http --check-status POST http://localhost:8080/api/flowers < test.http
      shell: bash
