name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Install HTTPie
      run: |
        sudo apt-get update
        sudo apt-get install httpie
      shell: bash

    - name: Start Spring Application
      run: |
        mvn spring-boot:run &
        sleep 10 # Wait for the Spring application to start

    - name: Test GET Request
      run: |
        http --check-status GET http://localhost:8080/api/v1/flowers
      shell: bash

    - name: Test POST Request
      run: |
        http --check-status POST http://localhost:8080/api/v1/flowers < test.http
      shell: bash

    - name: Stop Spring Boot Application
      run: |
        kill -15 $(lsof -t -i :8080)
        sleep 5
